version: '3.4'
services:
  php:
    build:
      context: ./php
    container_name: php_fpm
    networks:
      static_network:
        ipv4_address: 172.20.199.2
    ports:
      - 9000:9000
    volumes:
      - ./web/:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/log/:/var/www/log/
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - INSTALL_COMPOSER=${INSTALL_COMPOSER}
    restart: always
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      static_network:
        ipv4_address: 172.20.199.3
    ports:
      - 8181:80
      - 443:443
    volumes:
      - ./web/:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
      - ./logs/nginx/:/var/log/nginx
    depends_on:
      - php
  mysql:
    build:
      context: ./mysql
    container_name: mysql_db
    networks:
      static_network:
        ipv4_address: 172.20.199.4
    ports:
      - 3306:3306
    volumes:
      - ./mysql/custom_my.cnf:/etc/alternatives/my.cnf
      - mysqldata:/var/lib/mysql
    depends_on:
      - php
    external_links:
      - mysql_mysql_1:docker-mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    restart: always

networks:
  static_network:
    ipam:
      config:
        - subnet: 172.20.199.1/24
volumes:
  mysqldata:
    driver: local
